version: '3.2'
services:
  db:
    image: postgres:11
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1
